"""Markdown report generation for Kairon Crypto Agent."""

from datetime import datetime

from asset_explainability import generate_asset_explanation
from market_condition import (
    SIGNAL_ORDER,
    count_signals,
    determine_market_condition,
    explain_market_condition,
    get_market_condition_drivers,
)
from strategy_rules import SIGNAL_METADATA


def _format_asset_list(symbols: list[str]) -> str:
    """Return a readable asset list for report sections."""
    return ", ".join(symbols) if symbols else "none"


def _build_signal_legend_table() -> list[str]:
    """Build the educational signal legend as Markdown table rows."""
    lines = [
        "| Signal | Classification label | Signal interpretation | Research risk level | Research classification | Plain English meaning |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for signal in SIGNAL_ORDER:
        metadata = SIGNAL_METADATA[signal]
        lines.append(
            "| "
            f"{signal} | "
            f"{metadata['classification_label']} | "
            f"{metadata['signal_interpretation']} | "
            f"{metadata['research_risk_level']} | "
            f"{metadata['research_classification']} | "
            f"{metadata['plain_english_meaning']} |"
        )

    return lines


def _build_market_condition_section(results: list[dict]) -> list[str]:
    """Build the explainable market condition section."""
    market_condition = determine_market_condition(results)
    explanation = explain_market_condition(results, market_condition)
    signal_counts = count_signals(results)
    drivers = get_market_condition_drivers(results)

    lines = [
        "## Market Condition",
        "",
        f"- Classification: {market_condition}",
        f"- Explanation: {explanation}",
        "- Signal distribution:",
        "",
    ]

    for signal in SIGNAL_ORDER:
        count = signal_counts[signal]
        asset_label = "asset" if count == 1 else "assets"
        lines.append(f"  - {signal}: {count} {asset_label}")

    lines.extend(["", "- Main drivers:", ""])

    for driver in drivers:
        lines.append(f"  - {driver}")

    lines.extend(
        [
            "",
            (
                "- Research note: This market condition is based only on simple "
                "technical rules and should be interpreted as an educational "
                "classification, not as market advice."
            ),
        ]
    )

    return lines


def generate_markdown_report(results: list[dict], summary: dict) -> str:
    """Generate a Markdown market report from analysis results."""
    timestamp = datetime.now().isoformat(timespec="seconds")
    market_condition = determine_market_condition(results)
    market_interpretation = explain_market_condition(results, market_condition)

    lines = [
        "# Kairon Crypto Agent - Market Report",
        "",
        "## Timestamp",
        "",
        timestamp,
        "",
        *_build_market_condition_section(results),
        "",
        "## Educational Use Note",
        "",
        (
            "Signals are analytical classifications generated by simple technical "
            "rules. They are not trade orders, investment recommendations, or "
            "financial advice."
        ),
        "",
        "## Research Summary",
        "",
        f"- Best relative 7-day performer: {summary['strongest_asset']}",
        f"- Worst 7-day performer: {summary['weakest_asset']}",
        (
            "- Assets with positive technical structure: "
            f"{_format_asset_list(summary['assets_with_positive_structure'])}"
        ),
        (
            "- Assets classified as extended or technically cautious: "
            f"{_format_asset_list(summary['assets_extended_or_technical_caution'])}"
        ),
        (
            "- Assets requiring further observation: "
            f"{_format_asset_list(summary['assets_requiring_further_observation'])}"
        ),
        f"- Market interpretation: {market_interpretation}",
        "",
        "## Signal Legend",
        "",
        *_build_signal_legend_table(),
        "",
        "## Asset Analysis",
        "",
    ]

    for result in results:
        explanation = generate_asset_explanation(result)
        lines.extend(
            [
                f"### {result['symbol']}",
                "",
                f"- Current price: {result['current_price']:.2f}",
                f"- SMA 7: {result['sma_7']:.2f}",
                f"- SMA 21: {result['sma_21']:.2f}",
                f"- RSI 14: {result['rsi_14']:.2f}",
                f"- 7-day change: {result['change_7d']:.2f}%",
                f"- Signal: {result['signal']}",
                f"- Classification label: {result['classification_label']}",
                f"- Research risk level: {result['research_risk_level']}",
                f"- Research classification: {result['research_classification']}",
                f"- Signal interpretation: {result['signal_interpretation']}",
                f"- Plain English meaning: {result['plain_english_meaning']}",
                "",
                "#### Explanation",
                "",
                f"- Moving-average context: {explanation['moving_average_context']}",
                f"- RSI context: {explanation['rsi_context']}",
                f"- Recent performance: {explanation['performance_context']}",
                f"- Classification reasoning: {explanation['classification_reasoning']}",
                "",
                "#### Plain English Summary",
                "",
                explanation["concise_summary"],
                "",
            ]
        )

    lines.extend(
        [
            "## Research Context",
            "",
            (
                "Kairon also keeps a research layer based on the FGV Crypto vs "
                "Global Markets project, which suggests that global risk assets, "
                "especially NASDAQ, may be relevant context for BTC and major "
                "altcoins."
            ),
            "",
            "Reference: docs/research/fgv_crypto_global_markets_summary.md",
            "",
            "## Risk Note",
            "",
            (
                "This report is for educational analysis only. It does not execute "
                "trades and does not provide financial advice."
            ),
            "",
        ]
    )

    return "\n".join(lines)
